services:
    jenkins:
        build:
            context: .
            dockerfile: jenkins.Dockerfile
        ports:
            - "8080:8080"
        volumes:
            - jenkins_home:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
            - ${HOME}/.kube:/root/.kube
            - ${HOME}/.minikube:/root/.minikube
        environment:
            - DOCKER_HOST=unix:///var/run/docker.sock
        user: root
        group_add:
            - "998" # docker group on host

volumes:
    jenkins_home:
