services:
    jenkins:
        image: jenkins/jenkins:lts
        ports:
            - "8080:8080"
        volumes:
            - jenkins_home:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - DOCKER_HOST=unix:///var/run/docker.sock

volumes:
    jenkins_home:
