apiVersion: apps/v1
kind: Deployment
metadata:
    name: prism
spec:
    replicas: 2
    selector:
        matchLabels:
            app: prism
    template:
        metadata:
            labels:
                app: prism
        spec:
            containers:
                - name: prism
                  image: prism:latest
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 3000
                  envFrom:
                      - configMapRef:
                            name: prism-config
                      - secretRef:
                            name: prism-secrets
                  resources:
                      requests:
                          memory: "128Mi"
                          cpu: "100m"
                      limits:
                          memory: "256Mi"
                          cpu: "200m"
